version: 2.1

orbs:
  node: circleci/node@6.1.0

jobs: 
  build:
    working_directory: ~/generative-experiences
    docker:
    - image: cimg/node:20.17.0
    steps:
      - checkout
      - run: yarn install --frozen-lockfiles
      - run: yarn run build

workflows:
  build:
    jobs:
      - build
