# yaml-language-server: $schema=https://json.schemastore.org/github-issue-config.json
blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/algolia/generative-experiences/discussions/new?category=ideas&labels=triage&title=Feature%20request%3A%20
    about: Request a feature.
  - name: Ask a Question
    url: https://github.com/algolia/generative-experiences/discussions/new?category=q-a&labels=triage
    about: Ask questions and discuss with other community members.
